{
  doTestRecoveryAfterAnError(7,HadoopErrorSimulator.Kind.IOException);
}
