{
  try {
    body();
  }
 catch (  InterruptedException e) {
    if (log.isDebugEnabled())     log.debug("Caught interrupted exception: " + e);
    Thread.currentThread().interrupt();
  }
catch (  Throwable e) {
    U.error(log,"Runtime error caught during grid runnable execution: " + this,e);
    if (e instanceof Error)     throw e;
  }
 finally {
    cleanup();
    if (log.isDebugEnabled()) {
      if (isInterrupted())       log.debug("Grid runnable finished due to interruption without cancellation: " + getName());
 else       log.debug("Grid runnable finished normally: " + getName());
    }
  }
}
