{
  assertThrows(log,new Callable<Object>(){
    @Override public Object call() throws Exception {
      return data.casAsync(null,"val1","val2");
    }
  }
,NullPointerException.class,"Ouch! Argument cannot be null: key");
}
