{
  return res.getException() == null ? WAIT : res.getException().getCause() instanceof AssertionError ? REDUCE : FAILOVER;
}
