{
  assertThrows(log,new Callable<Object>(){
    @Override public Object call() throws Exception {
      return data.replaceAsync(null,"val");
    }
  }
,NullPointerException.class,"Ouch! Argument cannot be null: key");
  assertThrows(log,new Callable<Object>(){
    @Override public Object call() throws Exception {
      return data.replaceAsync("key",null);
    }
  }
,NullPointerException.class,"Ouch! Argument cannot be null: val");
}
